---
- name: Boot to Network Iso
  hosts: localhost
  becomes: yes
  tasks:
    - name: Boot to Network ISO
      dellemc.openmanage.idrac_os_deployment:
        idrac_ip: "{{ item.idracip }}"
        idrac_user: "root"
        idrac_password: "calvin"
        share_name: "10.2.220.112:/isofinished"
        iso_image: "{{ item.name }}.iso"
      loop: "{{ nested_info }}"
